/*
 * MapComposerPanel.java
 *
 * Created on July 31, 2007, 8:27 AM
 */
package edu.oregonstate.carto.mapcomposer.map.gui;

import edu.oregonstate.carto.mapcomposer.Layer;
import edu.oregonstate.carto.mapcomposer.Map;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import edu.oregonstate.carto.mapcomposer.map.style.Emboss;
import edu.oregonstate.carto.mapcomposer.map.style.Shadow;
import edu.oregonstate.carto.mapcomposer.map.style.Tint;
import ika.utils.FileUtils;
import ika.utils.GUIUtil;
import ika.utils.TransparentMacPanel;

public class MapComposerPanel extends javax.swing.JPanel {

    /**
     * This map is the model.
     */
    private Map map = new Map();
    /**
     * updating is true while any code in this class is modifying the GUI. While
     * this flag is true, event handlers should not modify the GUI to avoid
     * recursive calls to event handlers.
     */
    private boolean updating = false;
    
    /**
     * Creates new form MapComposerPanel
     */
    public MapComposerPanel() {
        initComponents();
        writeGUI();
    }

    /**
     * Returns the MapLayer currently selected by the user.
     *
     * @return
     */
    private Layer getSelectedMapLayer() {
        int index = layerList.getSelectedIndex();
        return index == -1 ? null : map.getLayer(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        blendingButtonGroup = new javax.swing.ButtonGroup();
        previewButton = new javax.swing.JButton();
        settingsPanel = new javax.swing.JPanel();
        visibleCheckBox = new javax.swing.JCheckBox();
        javax.swing.JLabel nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        javax.swing.JLabel urlLabel = new javax.swing.JLabel();
        javax.swing.JLabel blendingModeLabel = new javax.swing.JLabel();
        normalBlendingRadioButton = new javax.swing.JRadioButton();
        multiplyBlendingRadioButton = new javax.swing.JRadioButton();
        javax.swing.JLabel opacityLabel = new javax.swing.JLabel();
        opacitySlider = new javax.swing.JSlider();
        opacityNumberField = new ika.gui.NumberField();
        curveFilePathTextField = new javax.swing.JTextField();
        curveFileButton = new javax.swing.JButton();
        javax.swing.JLabel gradationCurveLabel = new javax.swing.JLabel();
        javax.swing.JLabel tintLabel = new javax.swing.JLabel();
        tintCheckBox = new javax.swing.JCheckBox();
        tintColorButton = new edu.oregonstate.carto.mapcomposer.gui.ColorButton();
        jSeparator1 = new javax.swing.JSeparator();
        urlTextField = new javax.swing.JTextField();
        javax.swing.JTabbedPane settingsTabbedPane = new javax.swing.JTabbedPane();
        javax.swing.JPanel texturePanel = new TransparentMacPanel();
        textureSelectionButton = new javax.swing.JButton();
        javax.swing.JLabel textureScaleLabel = new javax.swing.JLabel();
        textureScaleSlider = new javax.swing.JSlider();
        textureScaleNumberField = new ika.gui.NumberField();
        textureURLLabel = new javax.swing.JLabel();
        textureClearButton = new javax.swing.JButton();
        texturePreviewLabel = new javax.swing.JLabel();
        javax.swing.JPanel maskPanel = new TransparentMacPanel();
        maskComboBox = new javax.swing.JComboBox();
        invertMaskCheckBox = new javax.swing.JCheckBox();
        javax.swing.JLabel maskBlurLabel = new javax.swing.JLabel();
        maskBlurSlider = new javax.swing.JSlider();
        javax.swing.JPanel dropShadowPanel = new TransparentMacPanel();
        shadowCheckBox = new javax.swing.JCheckBox();
        shadowOffsetLabel = new javax.swing.JLabel();
        shadowOffsetSlider = new javax.swing.JSlider();
        shadowColorButton = new edu.oregonstate.carto.mapcomposer.gui.ColorButton();
        javax.swing.JLabel DropShadowFuzinessLabel = new javax.swing.JLabel();
        shadowFuziSlider = new javax.swing.JSlider();
        shadowFuziNumberField = new ika.gui.NumberField();
        javax.swing.JPanel embossPanel = new TransparentMacPanel();
        embossCheckBox = new javax.swing.JCheckBox();
        javax.swing.JLabel embossAzimuthLabel = new javax.swing.JLabel();
        embossAzimuthSlider = new javax.swing.JSlider();
        embossAzimuthNumberField = new ika.gui.NumberField();
        embossElevationSlider = new javax.swing.JSlider();
        embossElevationNumberField = new ika.gui.NumberField();
        javax.swing.JLabel embossElevationLabel = new javax.swing.JLabel();
        javax.swing.JLabel embossHeightLabel = new javax.swing.JLabel();
        embossHeightSlider = new javax.swing.JSlider();
        embossHeightNumberField = new ika.gui.NumberField();
        embossSoftnessSlider = new javax.swing.JSlider();
        javax.swing.JLabel embossSoftnessLabel = new javax.swing.JLabel();
        embossSoftnessNumberField = new ika.gui.NumberField();
        layersPanel = new javax.swing.JPanel();
        javax.swing.JLabel layersLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        layerList = new ika.gui.DraggableList();
        layerListToolBar = new javax.swing.JToolBar();
        addLayerButton = new javax.swing.JButton();
        removeLayerButton = new javax.swing.JButton();
        moveUpLayerButton = new javax.swing.JButton();
        moveDownLayerButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        previewButton.setText("Preview");
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(previewButton, gridBagConstraints);

        settingsPanel.setLayout(new java.awt.GridBagLayout());

        visibleCheckBox.setText("Visible");
        visibleCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        visibleCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        visibleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        settingsPanel.add(visibleCheckBox, gridBagConstraints);

        nameLabel.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        settingsPanel.add(nameLabel, gridBagConstraints);

        nameTextField.setText("Forest");
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        settingsPanel.add(nameTextField, gridBagConstraints);

        urlLabel.setText("URL:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        settingsPanel.add(urlLabel, gridBagConstraints);

        blendingModeLabel.setText("Blending Mode:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        settingsPanel.add(blendingModeLabel, gridBagConstraints);

        blendingButtonGroup.add(normalBlendingRadioButton);
        normalBlendingRadioButton.setText("Normal");
        normalBlendingRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        normalBlendingRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        normalBlendingRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        settingsPanel.add(normalBlendingRadioButton, gridBagConstraints);

        blendingButtonGroup.add(multiplyBlendingRadioButton);
        multiplyBlendingRadioButton.setText("Multiply");
        multiplyBlendingRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        multiplyBlendingRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        multiplyBlendingRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        settingsPanel.add(multiplyBlendingRadioButton, gridBagConstraints);

        opacityLabel.setText("Opacity:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        settingsPanel.add(opacityLabel, gridBagConstraints);

        opacitySlider.setValue(100);
        opacitySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        settingsPanel.add(opacitySlider, gridBagConstraints);

        opacityNumberField.setDoubleValue(100.0);
        opacityNumberField.setMax(100.0);
        opacityNumberField.setMin(0.0);
        opacityNumberField.setPattern("##0");
        opacityNumberField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numberFieldPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        settingsPanel.add(opacityNumberField, gridBagConstraints);

        curveFilePathTextField.setText("file:///Volumes/FireWireHD/Java/MapComposer/data/forestcurve.acv");
        curveFilePathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        settingsPanel.add(curveFilePathTextField, gridBagConstraints);

        curveFileButton.setText("File");
        curveFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curveFileButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        settingsPanel.add(curveFileButton, gridBagConstraints);

        gradationCurveLabel.setText("Gradation Curve (ACV):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        settingsPanel.add(gradationCurveLabel, gridBagConstraints);

        tintLabel.setText("Tint:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        settingsPanel.add(tintLabel, gridBagConstraints);

        tintCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tintCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tintCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        settingsPanel.add(tintCheckBox, gridBagConstraints);

        tintColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        settingsPanel.add(tintColorButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        settingsPanel.add(jSeparator1, gridBagConstraints);

        urlTextField.setText("url");
        urlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        settingsPanel.add(urlTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 10);
        add(settingsPanel, gridBagConstraints);

        texturePanel.setLayout(new java.awt.GridBagLayout());

        textureSelectionButton.setText("Select");
        textureSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textureSelectionButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        texturePanel.add(textureSelectionButton, gridBagConstraints);

        textureScaleLabel.setText("Texture Scale:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        texturePanel.add(textureScaleLabel, gridBagConstraints);

        textureScaleSlider.setMajorTickSpacing(50);
        textureScaleSlider.setMinimum(-100);
        textureScaleSlider.setMinorTickSpacing(10);
        textureScaleSlider.setPaintTicks(true);
        textureScaleSlider.setValue(0);
        textureScaleSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        texturePanel.add(textureScaleSlider, gridBagConstraints);

        textureScaleNumberField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numberFieldPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        texturePanel.add(textureScaleNumberField, gridBagConstraints);

        textureURLLabel.setFont(textureURLLabel.getFont().deriveFont(textureURLLabel.getFont().getSize()-3f));
        textureURLLabel.setText("Texture Path");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        texturePanel.add(textureURLLabel, gridBagConstraints);

        textureClearButton.setText("Clear");
        textureClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textureClearButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        texturePanel.add(textureClearButton, gridBagConstraints);

        texturePreviewLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        texturePreviewLabel.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        texturePanel.add(texturePreviewLabel, gridBagConstraints);

        settingsTabbedPane.addTab("Texture", texturePanel);

        maskPanel.setLayout(new java.awt.GridBagLayout());

        maskComboBox.setEditable(true);
        maskComboBox.setMaximumRowCount(25);
        maskComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        maskComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        maskPanel.add(maskComboBox, gridBagConstraints);

        invertMaskCheckBox.setText("Invert Mask");
        invertMaskCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        invertMaskCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        invertMaskCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        maskPanel.add(invertMaskCheckBox, gridBagConstraints);

        maskBlurLabel.setText("Blur Mask:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        maskPanel.add(maskBlurLabel, gridBagConstraints);

        maskBlurSlider.setMinorTickSpacing(10);
        maskBlurSlider.setPaintTicks(true);
        maskBlurSlider.setValue(0);
        maskBlurSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        maskPanel.add(maskBlurSlider, gridBagConstraints);

        settingsTabbedPane.addTab("Mask", maskPanel);

        dropShadowPanel.setLayout(new java.awt.GridBagLayout());

        shadowCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        shadowCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        shadowCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        dropShadowPanel.add(shadowCheckBox, new java.awt.GridBagConstraints());

        shadowOffsetLabel.setText("Offset:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        dropShadowPanel.add(shadowOffsetLabel, gridBagConstraints);

        shadowOffsetSlider.setMaximum(20);
        shadowOffsetSlider.setValue(1);
        shadowOffsetSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        dropShadowPanel.add(shadowOffsetSlider, new java.awt.GridBagConstraints());

        shadowColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        dropShadowPanel.add(shadowColorButton, new java.awt.GridBagConstraints());

        DropShadowFuzinessLabel.setText("Fuziness:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        dropShadowPanel.add(DropShadowFuzinessLabel, gridBagConstraints);

        shadowFuziSlider.setMaximum(20);
        shadowFuziSlider.setValue(10);
        shadowFuziSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        dropShadowPanel.add(shadowFuziSlider, gridBagConstraints);

        shadowFuziNumberField.setMax(90.0);
        shadowFuziNumberField.setMin(0.0);
        shadowFuziNumberField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numberFieldPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        dropShadowPanel.add(shadowFuziNumberField, gridBagConstraints);

        settingsTabbedPane.addTab("Drop Shadow", dropShadowPanel);

        embossPanel.setLayout(new java.awt.GridBagLayout());

        embossCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        embossCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        embossCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                embossCheckBoxStateChanged(evt);
            }
        });
        embossCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapComposerPanel.this.actionPerformed(evt);
            }
        });
        embossPanel.add(embossCheckBox, new java.awt.GridBagConstraints());

        embossAzimuthLabel.setText("Azimuth:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        embossPanel.add(embossAzimuthLabel, gridBagConstraints);

        embossAzimuthSlider.setMaximum(360);
        embossAzimuthSlider.setValue(315);
        embossAzimuthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        embossPanel.add(embossAzimuthSlider, gridBagConstraints);

        embossAzimuthNumberField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numberFieldPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        embossPanel.add(embossAzimuthNumberField, gridBagConstraints);

        embossElevationSlider.setMaximum(90);
        embossElevationSlider.setValue(45);
        embossElevationSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        embossPanel.add(embossElevationSlider, gridBagConstraints);

        embossElevationNumberField.setMax(90.0);
        embossElevationNumberField.setMin(0.0);
        embossElevationNumberField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numberFieldPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        embossPanel.add(embossElevationNumberField, gridBagConstraints);

        embossElevationLabel.setText("Elevation:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        embossPanel.add(embossElevationLabel, gridBagConstraints);

        embossHeightLabel.setText("Height:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        embossPanel.add(embossHeightLabel, gridBagConstraints);

        embossHeightSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        embossPanel.add(embossHeightSlider, gridBagConstraints);

        embossHeightNumberField.setMax(100.0);
        embossHeightNumberField.setMin(0.0);
        embossHeightNumberField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numberFieldPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        embossPanel.add(embossHeightNumberField, gridBagConstraints);

        embossSoftnessSlider.setMaximum(50);
        embossSoftnessSlider.setValue(10);
        embossSoftnessSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        embossPanel.add(embossSoftnessSlider, gridBagConstraints);

        embossSoftnessLabel.setText("Softness:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        embossPanel.add(embossSoftnessLabel, gridBagConstraints);

        embossSoftnessNumberField.setMax(50.0);
        embossSoftnessNumberField.setMin(0.0);
        embossSoftnessNumberField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numberFieldPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        embossPanel.add(embossSoftnessNumberField, gridBagConstraints);

        settingsTabbedPane.addTab("Emboss", embossPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(settingsTabbedPane, gridBagConstraints);

        layersPanel.setLayout(new java.awt.BorderLayout());

        layersLabel.setText("Layers");
        layersLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        layersPanel.add(layersLabel, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 132));

        layerList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        layerList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                layerListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(layerList);

        layersPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        layerListToolBar.setFloatable(false);

        addLayerButton.setText("+");
        addLayerButton.setMaximumSize(new java.awt.Dimension(22, 22));
        addLayerButton.setMinimumSize(new java.awt.Dimension(22, 22));
        addLayerButton.setPreferredSize(new java.awt.Dimension(22, 22));
        addLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLayerButtonActionPerformed(evt);
            }
        });
        layerListToolBar.add(addLayerButton);

        removeLayerButton.setText("-");
        removeLayerButton.setMaximumSize(new java.awt.Dimension(22, 22));
        removeLayerButton.setMinimumSize(new java.awt.Dimension(22, 22));
        removeLayerButton.setPreferredSize(new java.awt.Dimension(22, 22));
        removeLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLayerButtonActionPerformed(evt);
            }
        });
        layerListToolBar.add(removeLayerButton);

        moveUpLayerButton.setText("Up");
        moveUpLayerButton.setMaximumSize(new java.awt.Dimension(45, 22));
        moveUpLayerButton.setMinimumSize(new java.awt.Dimension(45, 22));
        moveUpLayerButton.setPreferredSize(new java.awt.Dimension(45, 22));
        moveUpLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpLayerButtonActionPerformed(evt);
            }
        });
        layerListToolBar.add(moveUpLayerButton);

        moveDownLayerButton.setText("Down");
        moveDownLayerButton.setMaximumSize(new java.awt.Dimension(45, 22));
        moveDownLayerButton.setMinimumSize(new java.awt.Dimension(45, 22));
        moveDownLayerButton.setPreferredSize(new java.awt.Dimension(45, 22));
        moveDownLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownLayerButtonActionPerformed(evt);
            }
        });
        layerListToolBar.add(moveDownLayerButton);

        layersPanel.add(layerListToolBar, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 13);
        add(layersPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * An event handler for number fields. Used by various number fields to read
     * freshly entered values.
     *
     * @param evt
     */
    private void numberFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_numberFieldPropertyChange
        if (this.updating || "value".equals(evt.getPropertyName()) == false) {
            return;
        }

        this.updating = true;
        try {
            this.opacitySlider.setValue((int) this.opacityNumberField.getDoubleValue());
            float textureScale = (float) this.textureScaleNumberField.getDoubleValue();
            this.writeTextureScale(textureScale);
            this.embossAzimuthSlider.setValue((int) this.embossAzimuthNumberField.getDoubleValue());
            this.embossElevationSlider.setValue((int) this.embossElevationNumberField.getDoubleValue());
            this.embossHeightSlider.setValue((int) (this.embossHeightNumberField.getDoubleValue() * 100));
            this.embossSoftnessSlider.setValue((int) this.embossSoftnessNumberField.getDoubleValue());
            this.shadowFuziSlider.setValue((int) this.shadowFuziNumberField.getDoubleValue());
        } finally {
            this.updating = false;
        }
    }//GEN-LAST:event_numberFieldPropertyChange

    /**
     * Event handler for selecting a Photoshop ACV curve file.
     *
     * @param evt
     */
    private void curveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curveFileButtonActionPerformed
        String msg = "Select an Adobe Photoshop ACV File";
        String filePath = FileUtils.askFile(GUIUtil.getOwnerFrame(this), msg, true);
        if (filePath == null) {
            return;
        }
        this.curveFilePathTextField.setText("file://" + filePath);
        this.readGUI();
    }//GEN-LAST:event_curveFileButtonActionPerformed

    /**
     * Event handler for changing the name of a layer.
     *
     * @param evt
     */
    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        this.readGUI();
        // update layers list to reflect new name.
        this.writeGUI();
    }//GEN-LAST:event_nameTextFieldActionPerformed

    /**
     * Event handler for moving a layer downwards in the layers hierarchy.
     *
     * @param evt
     */
    private void moveDownLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownLayerButtonActionPerformed
        int selectedLayerID = layerList.getSelectedIndex();
        if (selectedLayerID < 0 || selectedLayerID >= map.getLayerCount() - 1) {
            return;
        }
        Layer layer = map.removeLayer(selectedLayerID);
        map.addLayer(++selectedLayerID, layer);
        layerList.setSelectedIndex(selectedLayerID);
        writeGUI();
    }//GEN-LAST:event_moveDownLayerButtonActionPerformed

    /**
     * Event handler for moving a layer upwards in the layers hierarchy.
     *
     * @param evt
     */
    private void moveUpLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpLayerButtonActionPerformed
        int selectedLayerID = layerList.getSelectedIndex();
        if (selectedLayerID <= 0) {
            return;
        }
        Layer layer = map.removeLayer(selectedLayerID);
        map.addLayer(--selectedLayerID, layer);
        this.layerList.setSelectedIndex(selectedLayerID);
        this.writeGUI();
    }//GEN-LAST:event_moveUpLayerButtonActionPerformed

    /**
     * Event handler for removing a layer.
     */
    private void removeLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLayerButtonActionPerformed
        int selectedLayerID = this.layerList.getSelectedIndex();
        if (selectedLayerID < 0) {
            return;
        }
        this.map.removeLayer(selectedLayerID);
        this.writeGUI();
        this.layerList.setSelectedIndex(--selectedLayerID);
    }//GEN-LAST:event_removeLayerButtonActionPerformed

    /**
     * Event handler to generate a preview of the current map. Either displays
     * an image in a new window, or creates tiles and has the default web
     * browser render them.
     *
     * @param evt
     */
    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
    /*    try {
            this.readGUI();

            if (this.imageCollection instanceof DirectoryImageCollection) {
                MapTileGenerator generator = new MapTileGenerator(getMap(), imageCollection);
                BufferedImage image = generator.createTile("map");
                ika.utils.ImageUtils.displayImageInWindow(image);
            } else if (this.imageCollection instanceof TiledImageCollection) {

                //Writing resulting tiles to a temporary directory.
                File tempTilesDir = FileUtils.createTempDirectory();
                MapTileGenerator generator = new MapTileGenerator(map, this.imageCollection);
                map.setTiledImage(new TiledImage(tempTilesDir.getAbsolutePath()));
                File refDir = ((TiledImageCollection) (imageCollection)).getRefDir();
                map.getTiledImage().createTiledImage(refDir, true, generator, null);

                File styleFile = new File(tempTilesDir, FileUtils.getFileNameWithoutExtension(tempTilesDir.getName()));
                this.map.marshal(styleFile.getAbsolutePath() + ".xml");

                //Display results in a webpage
                File htmlFile = copyHTML(tempTilesDir.getPath());
                Desktop.getDesktop().browse(htmlFile.toURI());
            }

        } catch (Exception exc) {
            ErrorDialog.showErrorDialog("Could not render the preview", exc);
        }*/
    }//GEN-LAST:event_previewButtonActionPerformed

    /**
     * A general event handler for when a slider value changes. Used by various
     * sliders.
     *
     * @param evt
     */
    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        if (this.updating) {
            return;
        }

        this.updating = true;
        try {
            this.opacityNumberField.setDoubleValue(opacitySlider.getValue());
            this.textureScaleNumberField.setDoubleValue(this.readTextureScale());
            this.embossAzimuthNumberField.setDoubleValue(embossAzimuthSlider.getValue());
            this.embossElevationNumberField.setDoubleValue(embossElevationSlider.getValue());
            this.embossHeightNumberField.setDoubleValue(embossHeightSlider.getValue() / 100.);
            this.embossSoftnessNumberField.setDoubleValue(embossSoftnessSlider.getValue());
            this.shadowFuziNumberField.setDoubleValue(shadowFuziSlider.getValue());
        } finally {
            this.updating = false;
        }

        if (((JSlider) evt.getSource()).getValueIsAdjusting() == false) {
            this.readGUI();
        }
    }//GEN-LAST:event_sliderStateChanged

    /**
     * A generic event handler for different kinds of action events. Used by
     * various components.
     *
     * @param evt
     */
    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        this.readGUI();
    }//GEN-LAST:event_actionPerformed

    /**
     * Event handler called when the selection in the layers list changes.
     *
     * @param evt
     */
    private void layerListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_layerListValueChanged
        this.writeGUI();
    }//GEN-LAST:event_layerListValueChanged

    /**
     * Add a layer.
     *
     * @param evt
     */
    private void addLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLayerButtonActionPerformed
        String name = JOptionPane.showInputDialog(this, "Layer Name", "Layer");
        if (name == null) {
            return;
        }

        int selectedLayerID = this.layerList.getSelectedIndex();
        this.map.addLayer(++selectedLayerID, new Layer(name));
        this.writeGUI();
        this.layerList.setSelectedIndex(selectedLayerID);
    }//GEN-LAST:event_addLayerButtonActionPerformed

    private void embossCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_embossCheckBoxStateChanged
        if (updating) {
            return;
        }
        if (this.embossCheckBox.isSelected()) {
            this.embossHeightSlider.setEnabled(true);
            this.embossHeightNumberField.setEnabled(true);
            this.embossSoftnessSlider.setEnabled(true);
            this.embossSoftnessNumberField.setEnabled(true);
            this.embossAzimuthSlider.setEnabled(true);
            this.embossAzimuthNumberField.setEnabled(true);
            this.embossElevationSlider.setEnabled(true);
            this.embossElevationNumberField.setEnabled(true);
        } else {
            this.embossHeightSlider.setEnabled(false);
            this.embossHeightNumberField.setEnabled(false);
            this.embossSoftnessSlider.setEnabled(false);
            this.embossSoftnessNumberField.setEnabled(false);
            this.embossAzimuthSlider.setEnabled(false);
            this.embossAzimuthNumberField.setEnabled(false);
            this.embossElevationSlider.setEnabled(false);
            this.embossElevationNumberField.setEnabled(false);
        }
    }//GEN-LAST:event_embossCheckBoxStateChanged

    /**
     * Event handler to add a texture image file or a texture tile set to the
     * selected layer.
     *
     * @param evt
     */
    private void textureSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textureSelectionButtonActionPerformed
        /*try {
            String path = null;
            if (imageCollection instanceof DirectoryImageCollection) {
                String msg = "Select a Texture Image Tile";
                path = FileUtils.askFile(GUIUtil.getOwnerFrame(this), msg, true);
            } else if (imageCollection instanceof TiledImageCollection) {
                String msg = "Select a Directory with a Texture Tile Set";
                path = FileUtils.askDirectory(GUIUtil.getOwnerFrame(this), msg, true, null);
            }
            if (path != null) {
                MapLayer layer = getSelectedMapLayer();
                if (layer != null) {
                    layer.setTextureURL(path);
                }
                writeGUI();
            }
        } catch (Exception ex) {
            String msg = "Error";
            String title = "The texture could not be loaded.";
            ErrorDialog.showErrorDialog(msg, title, ex, this);
        }
    */
    }//GEN-LAST:event_textureSelectionButtonActionPerformed

    /**
     * Event handler to remove the current texture from the selected layer.
     *
     * @param evt
     */
    private void textureClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textureClearButtonActionPerformed
        Layer layer = getSelectedMapLayer();
        if (layer != null) {
            layer.setTextureURL(null);
        }
        writeGUI();
    }//GEN-LAST:event_textureClearButtonActionPerformed

    private void urlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlTextFieldActionPerformed

    /**
     * Updates the value of the texture scale slider
     *
     * @param textureScale
     */
    private void writeTextureScale(float textureScale) {
        if (textureScale > 1) {
            textureScale = -100f + textureScale * 100f;
        } else {
            textureScale = -200 + textureScale * 200f;
        }
        this.textureScaleSlider.setValue((int) (textureScale));
    }

    /**
     * Reads the value of the texture scale slider.
     *
     * @return
     */
    private float readTextureScale() {
        // scale from [-100, +100] to [0.5, 2]
        float textureScale = this.textureScaleSlider.getValue();
        if (textureScale > 0) {
            textureScale = 1f + textureScale / 100f;
        } else {
            textureScale = 1f + textureScale * 0.5f / 100f;
        }
        return textureScale;
    }

    /**
     * Writes settings of the currently selected layer to the GUI.
     */
    final void writeGUI() {
        if (this.updating) {
            return;
        }

        try {
            this.updating = true;

            // update the layers list
            int selectedID = layerList.getSelectedIndex();
            layerList.setListData(map.getLayers());
            layerList.setSelectedIndex(selectedID);

            Layer selectedLayer = getSelectedMapLayer();

            // enable or disable user interface elements depending on whether
            // a layer is currently selected
            final boolean on = selectedLayer != null;
            this.visibleCheckBox.setEnabled(on);
            this.nameTextField.setEnabled(on);
            this.urlTextField.setEnabled(on);
            this.normalBlendingRadioButton.setEnabled(on);
            this.multiplyBlendingRadioButton.setEnabled(on);
            this.opacitySlider.setEnabled(on);
            this.opacityNumberField.setEnabled(on);
            this.curveFilePathTextField.setEnabled(on);
            this.curveFileButton.setEnabled(on);
            this.tintCheckBox.setEnabled(on);
            this.tintColorButton.setEnabled(on);
            this.textureSelectionButton.setEnabled(on);
            this.textureClearButton.setEnabled(on);
            this.textureURLLabel.setEnabled(on);
            this.textureScaleSlider.setEnabled(on);
            this.maskComboBox.setEnabled(on);
            this.maskBlurSlider.setEnabled(on);
            this.invertMaskCheckBox.setEnabled(on);
            this.shadowCheckBox.setEnabled(on);
            this.shadowOffsetSlider.setEnabled(on);
            this.shadowColorButton.setEnabled(on);
            this.shadowFuziNumberField.setEnabled(on);
            this.shadowFuziSlider.setEnabled(on);
            this.embossCheckBox.setEnabled(on);
            this.embossHeightSlider.setEnabled(on);
            this.embossHeightNumberField.setEnabled(on);
            this.embossSoftnessSlider.setEnabled(on);
            this.embossSoftnessNumberField.setEnabled(on);
            this.embossAzimuthSlider.setEnabled(on);
            this.embossAzimuthNumberField.setEnabled(on);
            this.embossElevationSlider.setEnabled(on);
            this.embossElevationNumberField.setEnabled(on);
            this.previewButton.setEnabled(on);
            this.removeLayerButton.setEnabled(on);
            this.moveUpLayerButton.setEnabled(on && selectedID != 0);
            this.moveDownLayerButton.setEnabled(on && selectedID != map.getLayerCount() - 1);

            if (selectedLayer == null) {
                this.nameTextField.setText(null);
                this.urlTextField.setText(null);
                this.curveFilePathTextField.setText(null);
                this.maskComboBox.setSelectedItem(null);
                return;
            }

            this.visibleCheckBox.setSelected(selectedLayer.isVisible());
            this.nameTextField.setText(selectedLayer.getName());
            // FIXME
            this.urlTextField.setText(selectedLayer.getName());
            // FIXME this.imageComboBox.setSelectedItem(selectedLayer.getImageName());

            // blending
            this.normalBlendingRadioButton.setSelected(selectedLayer.isBlendingNormal());

            // opacity
            this.opacitySlider.setValue((int) (selectedLayer.getOpacity() * 100));
            this.opacityNumberField.setDoubleValue(selectedLayer.getOpacity() * 100);

            // curve
            this.curveFilePathTextField.setText(selectedLayer.getCurveURL());

            // tinting
            if (selectedLayer.getTint() != null) {
                this.tintCheckBox.setSelected(true);
                this.tintColorButton.setColor(selectedLayer.getTint().getTintColor());
            } else {
                this.tintCheckBox.setSelected(false);
            }

            // texture
            textureURLLabel.setText(selectedLayer.getTextureURL());
            this.writeTextureScale(selectedLayer.getTextureScale());
            this.textureScaleNumberField.setDoubleValue(selectedLayer.getTextureScale());
            previewTexture();

            // mask
            // FIXME this.maskComboBox.setSelectedItem(selectedLayer.getMaskName());
            this.invertMaskCheckBox.setSelected(selectedLayer.isInvertMask());
            this.maskBlurSlider.setValue((int) (selectedLayer.getMaskBlur() * 10f));

            // drop shadow
            if (selectedLayer.getShadow() != null) {
                this.shadowCheckBox.setSelected(true);
                this.shadowOffsetSlider.setValue(selectedLayer.getShadow().getShadowOffset());
                this.shadowFuziSlider.setValue(selectedLayer.getShadow().getShadowFuziness());
                this.shadowColorButton.setColor(selectedLayer.getShadow().getShadowColor());
            } else {
                this.shadowCheckBox.setSelected(false);
            }

            // embossing
            if (selectedLayer.getEmboss() != null) {
                this.embossCheckBox.setSelected(true);
                this.embossHeightSlider.setEnabled(true);
                this.embossSoftnessSlider.setEnabled(true);
                this.embossAzimuthSlider.setEnabled(true);
                this.embossElevationSlider.setEnabled(true);

                this.embossHeightSlider.setValue((int) (selectedLayer.getEmboss().getEmbossHeight() * 100f));
                this.embossHeightNumberField.setDoubleValue(selectedLayer.getEmboss().getEmbossHeight());
                this.embossSoftnessSlider.setValue((int) selectedLayer.getEmboss().getEmbossSoftness());
                this.embossSoftnessNumberField.setDoubleValue(selectedLayer.getEmboss().getEmbossSoftness());
                this.embossAzimuthSlider.setValue((int) selectedLayer.getEmboss().getEmbossAzimuth());
                this.embossAzimuthNumberField.setDoubleValue(selectedLayer.getEmboss().getEmbossAzimuth());
                this.embossElevationSlider.setValue((int) selectedLayer.getEmboss().getEmbossElevation());
                this.embossElevationNumberField.setDoubleValue(selectedLayer.getEmboss().getEmbossElevation());
            } else {
                this.embossCheckBox.setSelected(false);
            }

        } finally {
            this.updating = false;
        }
    }

    /**
     * Displays a piece of texture in a preview thumbnail.
     */
    private void previewTexture() {
        /*
        // tiled textures are not currently supported
        if (imageCollection instanceof DirectoryImageCollection == false) {
            texturePreviewLabel.setIcon(null);
            return;
        }
        String textureURL = getSelectedMapLayer().getTextureURL();
        if (textureURL == null) {
            texturePreviewLabel.setIcon(null);
            return;
        }
        try {
            int h = texturePreviewLabel.getHeight();
            int w = texturePreviewLabel.getWidth();
            BufferedImage texturePatch = ImageIO.read(new File(textureURL));
            TileImageFilter tiler = new TileImageFilter(w, h);
            BufferedImage img = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
            img = tiler.filter(texturePatch, img);
            texturePreviewLabel.setIcon(new ImageIcon(img));
        } catch (Exception ex) {
            texturePreviewLabel.setIcon(null);
        }
        */ 
    }

    /**
     * Reads user settings from the GUI and passes the settings to the currently
     * selected layer.
     *
     * @throws MalformedURLException
     * @throws IOException
     */
    public void readGUI() {
        if (this.updating) {
            return;
        }
        Layer layer = getSelectedMapLayer();
        if (layer == null) {
            return;
        }

        layer.setVisible(this.visibleCheckBox.isSelected());
        layer.setName(this.nameTextField.getText());
        layer.setBlending(this.normalBlendingRadioButton.isSelected()
                ? Layer.BlendType.NORMAL : Layer.BlendType.MULTIPLY);
        layer.setOpacity(this.opacitySlider.getValue() / 100.f);
        layer.setCurveURL(this.curveFilePathTextField.getText());

        // FIXME layer.setImageName((String) this.imageComboBox.getSelectedItem());

        // mask
        // FIXME layer.setMaskName((String) this.maskComboBox.getSelectedItem());
        layer.setInvertMask(this.invertMaskCheckBox.isSelected());
        layer.setMaskBlur(this.maskBlurSlider.getValue() / 10f);

        // tint
        if (this.tintCheckBox.isSelected()) {
            Tint tint = new Tint();
            tint.setTintColor(this.tintColorButton.getColor());
            layer.setTint(tint);
        } else {
            layer.setTint(null);
        }

        // texture
        layer.setTextureScale(this.readTextureScale());

        // shadow
        if (this.shadowCheckBox.isSelected()) {
            Shadow shadow = new Shadow();
            shadow.setShadowOffset(this.shadowOffsetSlider.getValue());
            shadow.setShadowColor(this.shadowColorButton.getColor());
            shadow.setShadowFuziness(this.shadowFuziSlider.getValue());
            layer.setShadow(shadow);
        } else {
            layer.setShadow(null);
        }


        // emboss
        if (this.embossCheckBox.isSelected()) {
            Emboss emboss = new Emboss();
            emboss.setEmbossHeight(this.embossHeightSlider.getValue() / 100f);
            emboss.setEmbossSoftness(this.embossSoftnessSlider.getValue());
            emboss.setEmbossAzimuth(this.embossAzimuthSlider.getValue());
            emboss.setEmbossElevation(this.embossElevationSlider.getValue());
            layer.setEmboss(emboss);
        } else {
            layer.setEmboss(null);
        }
    }

    public File copyHTML(String path) throws IOException {
        URL inputUrl = getClass().getResource("/Local_Tiles_TMS.html");
        File dest = new File(path + "/Local_Tiles_TMS.html");
        // FIXME org.apache.commons.io.FileUtils.copyURLToFile(inputUrl, dest);
        return dest;
    }
    
    public Map getMap() {
        return map;
    }

    public void setMap(Map map) {
        this.map = map;
        layerList.setSelectedIndex(layerList.getFirstVisibleIndex());        
        this.writeGUI();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLayerButton;
    private javax.swing.ButtonGroup blendingButtonGroup;
    private javax.swing.JButton curveFileButton;
    private javax.swing.JTextField curveFilePathTextField;
    private ika.gui.NumberField embossAzimuthNumberField;
    private javax.swing.JSlider embossAzimuthSlider;
    private javax.swing.JCheckBox embossCheckBox;
    private ika.gui.NumberField embossElevationNumberField;
    private javax.swing.JSlider embossElevationSlider;
    private ika.gui.NumberField embossHeightNumberField;
    private javax.swing.JSlider embossHeightSlider;
    private ika.gui.NumberField embossSoftnessNumberField;
    private javax.swing.JSlider embossSoftnessSlider;
    private javax.swing.JCheckBox invertMaskCheckBox;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private ika.gui.DraggableList layerList;
    private javax.swing.JToolBar layerListToolBar;
    private javax.swing.JPanel layersPanel;
    private javax.swing.JSlider maskBlurSlider;
    private javax.swing.JComboBox maskComboBox;
    private javax.swing.JButton moveDownLayerButton;
    private javax.swing.JButton moveUpLayerButton;
    private javax.swing.JRadioButton multiplyBlendingRadioButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton normalBlendingRadioButton;
    private ika.gui.NumberField opacityNumberField;
    private javax.swing.JSlider opacitySlider;
    private javax.swing.JButton previewButton;
    private javax.swing.JButton removeLayerButton;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JCheckBox shadowCheckBox;
    private edu.oregonstate.carto.mapcomposer.gui.ColorButton shadowColorButton;
    private ika.gui.NumberField shadowFuziNumberField;
    private javax.swing.JSlider shadowFuziSlider;
    private javax.swing.JLabel shadowOffsetLabel;
    private javax.swing.JSlider shadowOffsetSlider;
    private javax.swing.JButton textureClearButton;
    private javax.swing.JLabel texturePreviewLabel;
    private ika.gui.NumberField textureScaleNumberField;
    private javax.swing.JSlider textureScaleSlider;
    private javax.swing.JButton textureSelectionButton;
    private javax.swing.JLabel textureURLLabel;
    private javax.swing.JCheckBox tintCheckBox;
    private edu.oregonstate.carto.mapcomposer.gui.ColorButton tintColorButton;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JCheckBox visibleCheckBox;
    // End of variables declaration//GEN-END:variables

}
